### ISSUE TITLE
Does not compile with gcc 7.2.1

### ISSUE THREAD

**Issue by sijohans** [assaabloy-ppi/binson-c-light#24]
Does not compile with gcc 7.2.1 with the following flags: **-Wall -Wextra -Wpedantic -Werror -std=c99**

```
$ gcc -c binson_light.c -Wall -Wextra -Wpedantic -Werror -std=c99 -o binson_light.o
binson_light.c: In function ‘binson_parser_advance’:
binson_light.c:477:16: error: this statement may fall through [-Werror=implicit-fallthrough=]
             if (CHECKBITMASK(pp->state, BINSON_PARSER_STATE_IN_BLOCK |  /* CASE: first OBJECT item's name */
                ^
binson_light.c:481:10: note: here
          case BINSON_PARSER_STATE_BLOCK:  /* pp->state => BINSON_PARSER_STATE_BLOCK */
          ^~~~
binson_light.c:482:16: error: this statement may fall through [-Werror=implicit-fallthrough=]
             if (CHECKBITMASK(pp->state, BINSON_PARSER_STATE_IN_BLOCK |  /* CASE: nested blocks */
                ^
binson_light.c:488:10: note: here
          case BINSON_PARSER_STATE_IN_BLOCK:  /* pp->state => BINSON_PARSER_STATE_IN_BLOCK */
          ^~~~
binson_light.c:489:16: error: this statement may fall through [-Werror=implicit-fallthrough=]
             if (CHECKBITMASK(pp->state, BINSON_PARSER_STATE_BLOCK))
                ^
binson_light.c:492:10: note: here
          case BINSON_PARSER_STATE_IN_BLOCK_END:  /* pp->state => BINSON_PARSER_STATE_IN_BLOCK_END */
          ^~~~
binson_light.c:493:16: error: this statement may fall through [-Werror=implicit-fallthrough=]
             if (CHECKBITMASK(pp->state, BINSON_PARSER_STATE_IN_BLOCK |  /* CASE: empty block */
                ^
binson_light.c:498:10: note: here
          case BINSON_PARSER_STATE_BLOCK_END:  /* pp->state => BINSON_PARSER_STATE_BLOCK_END */
          ^~~~
binson_light.c:499:16: error: this statement may fall through [-Werror=implicit-fallthrough=]
             if (CHECKBITMASK(pp->state, BINSON_PARSER_STATE_IN_BLOCK_END))
                ^
binson_light.c:502:10: note: here
          case BINSON_PARSER_STATE_VAL:  /* pp->state => BINSON_PARSER_STATE_VAL */
          ^~~~
binson_light.c:503:16: error: this statement may fall through [-Werror=implicit-fallthrough=]
             if (CHECKBITMASK(pp->state, BINSON_PARSER_STATE_IN_BLOCK |  /* CASE: first ARRAY value */
                ^
binson_light.c:508:10: note: here
          case BINSON_PARSER_STATE_UNDEFINED:  /* pp->state => BINSON_PARSER_STATE_UNDEFINED */
          ^~~~
binson_light.c:509:16: error: this statement may fall through [-Werror=implicit-fallthrough=]
             if (CHECKBITMASK(pp->state, BINSON_PARSER_STATE_BLOCK_END))  /* CASE: top block end */
                ^
binson_light.c:512:10: note: here
          default:

```

**Comment by ppmag** [comment]
Thank you!

**Comment by ppmag** [comment]
Fixed via  adding:
`__attribute__ ((fallthrough));`
since fallthroughs are by-design there.... to prevent code spaghetti.

**Comment by sijohans** [comment]
I had the same problem in the salt-channel-c project. I found this post: https://developers.redhat.com/blog/2017/03/10/wimplicit-fallthrough-in-gcc-7/

Depending on the level of Wimplicit-fallthrough just a comment could also fix this issue.

**Comment by ppmag** [comment]
Thank you, comment way is much better since is portable! Fixed.
